version: '{build}'
os: Windows Server 2012
environment:
  matrix:
    - JAVA_HOME: C:\Tools\jdk-12.0.2
install:
  - ps: choco install maven
  - ps: src/build/scripts/rustup.ps1
  - ps: $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
  - mvn --version
  - rustc --version
  - cargo --version
build_script:
  - mvn --batch-mode clean package -DskipTests
test_script:
  - mvn --batch-mode clean package
artifacts:
  - path: target/rust-libs/*
cache:
  - C:\Users\appveyor\.m2