version: '{build}'
os: Windows 10
environment:
  matrix:
    - JAVA_HOME: C:\Tools\jdk-12.0.2
install:
  - mvn --version
  - java --version

build_script:
  - mvn --batch-mode clean package -DskipTests
test_script:
  - mvn --batch-mode clean package
artifacts:
  - path: target/java-libs/*
cache:
  - C:\Users\appveyor\.m2